### ISSUE TITLE
Fedora 33 Not a valid CA certificate: certutil: certificate is invalid: The certificate was signed using a signature algorithm that is disabled because it is not secure.

### ISSUE THREAD

**Issue by tayeh** [freeipa/freeipa-letsencrypt#31] opened 2021-01-27 11:02 UTC
trying to use on fedora 33 

```
[root@account freeipa-letsencrypt]# ./setup-le.sh 
Last metadata expiration check: 1:37:21 ago on Wed 27 Jan 2021 09:21:34 AM UTC.
Package certbot-1.11.0-1.fc33.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
Installing CA certificate, please wait
Not a valid CA certificate: certutil: certificate is invalid: The certificate was signed using a signature algorithm that is disabled because it is not secure.
 (visit http://www.freeipa.org/page/Troubleshooting for troubleshooting guide)
The ipa-cacert-manage command failed.

```

**Comment by rcritten** [comment] 2021-01-27 13:49
This is a duplicate of issue 25. See PR 30 for a solution.

**Closed as completed by rcritten** 2021-01-27 13:49 UTC
