### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by ictinc** [freeipa/freeipa-letsencrypt#29] opened 2020-12-29 03:31 UTC
Hi there,
I'm completely new to FreeIPA and my knowledge is limited. I managed to get everything running and used this tool to setup an LE certficate. The webinterface now shows a valid certificate.
However when I run the command:
`sudo ipa config-mod --defaultshell=/bin/bash`
I get a CERTIFICATE_VERIFY_FAILED could not connect to https://domain/ipa/json error message.
I'm not sure how to overcome this issue.
I would use the default certificates if it wasn't for firefox complaining about the serial of the certificate being the same as a previous one. I had an installation before but decided to start a fresh install.
I went through the steps to remove the certificate from firefox but was unable to locate it under authorities, I did manage to find it under servers but that didn't solve the issue. To get around this I thought an easy fix would be to use LE certificates instead.

Any ideas as to how I would overcome the issue CERTIFICATE_VERIFY_FAILED would be much appreciated.

Kind regards,
Ronald.

**Comment by thinkmassive** [comment] 2021-01-20 02:00
Hi @ictinc, this is a duplicate of [issue 25](https://github.com/freeipa/freeipa-letsencrypt/issues/25). In case this is still blocking you I recommend visiting that issue and [PR 30](https://github.com/freeipa/freeipa-letsencrypt/pull/30). With that info, and the [code from afrothundaaaa](https://github.com/afrothundaaaa/freeipa-letsencrypt), you should get a working solution.

**Closed as completed** 2021-01-27 13:49 UTC
